---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-ingress-controller
  namespace: default

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: k8s-ingress-controller
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - endpoints
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: k8s-ingress-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-ingress-controller
subjects:
  - kind: ServiceAccount
    name: k8s-ingress-controller
    namespace: default

---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: k8s-ingress-controller
  labels:
    app: ingress-controller
spec:
  selector:
    matchLabels:
      app: ingress-controller
  template:
    metadata:
      labels:
        app: ingress-controller
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: k8s-ingress-controller
      containers:
        - name: k8s-ingress-controller
          image: cnych/k8s-ingress-controller:v0.1
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
